[[plugins]]
repo  = 'Quramy/tsuquyomi'
on_ft = ['typescript']

# 特定のコマンドを打ったら読み込む
[[plugins]]
repo      = 'thinca/vim-prettyprint'
on_cmd    = ['PP', 'PrettyPrint']

# 特定のマッピングを使ったら読み込む
# 又、gvim でしか利用しない
[[plugins]]
repo   = 'thinca/vim-fontzoom'
on_cmd = ['Fontzoom']
on_map = ['<Plug>(fontzoom-']
gui    = 1

[[plugins]]
repo = 'Shougo/neosnippet'
on_i = 1
on_ft = 'snipppet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_i = 1

# Markdownをブラウザと同期して表示
[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
# build = 'sh -c "cd app & yarn install"'
hook_post_update = '''

  " let s:dein_dir = expand('~/.cache/dein')
  " let s:dein_repo_dir = s:dein_dir . '/repos/github.com/iamcco/markdown-preview.nvim'
  " let s:cd_cmd = 'cd ' . s:dein_repo_dir . '/app'
  " let s:yarn = 'yarn install'
  "
  " echo expand("%:p:h")
  " cd ~/.cache/dein/repos/github.com/iamcco/markdown-preview.nvim/app/
  " echo expand("%:p:h")
  " sh pwd
  " " sh -c 'yarn install'

  source ~/.config/nvim/plugins/markdown-preview.rc.vim
  let g:dein#plugin.build = 'sh -c "cd app & yarn install"'
'''

